# Generated by Django 6.0 on 2026-01-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_document_page_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='page_metadata',
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='bboxes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
