# Generated by Django 6.0 on 2026-01-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_document_page_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedfunddata',
            name='management_fee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='extractedfunddata',
            name='redemption_fee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='extractedfunddata',
            name='subscription_fee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='extractedfunddata',
            name='switching_fee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
