# Generated by Django 6.0 on 2026-01-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_mistral_ocr_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
