# Generated by Django 6.0 on 2026-01-07 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_document_edit_count_document_last_edited_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('changes', models.JSONField(default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='api.document')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['document', '-changed_at'], name='api_documen_documen_90f829_idx')],
            },
        ),
    ]
