# Generated by Django 6.0 on 2026-01-07 07:48

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_documentchangelog'),
    ]

    operations = [
        VectorExtension()
    ]
