# Generated by Django 5.2.10 on 2026-02-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_document_rag_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='markdown_file',
            field=models.FileField(blank=True, null=True, upload_to='markdown_outputs/%Y/%m/%d/'),
        ),
    ]
