# Generated by Django 5.2.10 on 2026-02-11 07:24

import pgvector.django.vector
from django.db import migrations


def purge_old_chunks(apps, schema_editor):
    DocumentChunk = apps.get_model('api', 'DocumentChunk')
    DocumentChunk.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_document_markdown_file'),
    ]

    operations = [
        # Existing HNSW index depends on vector dimensions; drop before altering.
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS chunk_embedding_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Old embeddings are incompatible with the new dimension; purge and re-ingest.
        migrations.RunPython(purge_old_chunks, reverse_code=migrations.RunPython.noop),

        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),

        # Recreate HNSW index for cosine distance.
        migrations.RunSQL(
            sql=(
                "CREATE INDEX chunk_embedding_idx ON api_documentchunk "
                "USING hnsw (embedding vector_cosine_ops) "
                "WITH (m=16, ef_construction=64);"
            ),
            reverse_sql="DROP INDEX IF EXISTS chunk_embedding_idx;",
        ),
    ]
